apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale-kube-proxy.fullname" . }}
  labels:
    {{- include "tailscale-kube-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTHKEY: {{ .Values.ts.authKey | quote }}