{{- if not .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tailscale-kube-proxy.fullname" . }}
  labels:
    {{- include "tailscale-kube-proxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tailscale-kube-proxy.labels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443
{{- end -}}