{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "tailscale-kube-proxy.stateSecretName" .)) -}}

{{- if not $existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale-kube-proxy.stateSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailscale-kube-proxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data: {}
{{- end -}}